version: "3"

services:
  qb-db:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  qb-bot:
    container_name: qb-bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
      - "/app/node_modules"
    depends_on:
      qb-db:
        condition: service_healthy