apiVersion: v1
kind: Service
metadata:
  name: queue-bot
  labels:
    app: queue-bot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: queue-bot
  selector:
    app: queue-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-bot
  labels:
    app: queue-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-bot
  template:
    metadata:
      labels:
        app: queue-bot
    spec:
      containers:
        # [START db_container]
        - name: database
          image: postgres:9.6-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: password
          resources:
            requests:
              cpu: 25m
              memory: "0.05G"
        - name: queue-bot
          image: gcr.io/htn-techyon/queue-bot
          command: ["npm"]
          args: ["start"]
          env:
            - name: QB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: htn-2020-queue-bot-token
                  key: token
            - name: QB_TOP_GG_TOKEN
              value: ""
            - name: QB_COLOR
              value: "#478E81"
            - name: QB_GRACE_PERIOD
              value: "0"
            - name: QB_JOIN_EMOJI
              value: "⤴"
            - name: QB_PERMISSIONS_REGEXP
              value: "\\bmod(erator)?s?\\b|\\badmin(istrator)?s?\\b"
            - name: QB_PREFIX
              value: "!"
            - name: QB_DB_TYPE
              value: "postgresql"
            - name: QB_DB_HOST
              value: "localhost"
            - name: QB_DB_NAME
              value: "postgres"
            - name: QB_DB_USERNAME
              value: "postgres"
            - name: QB_DB_PASSWORD
              value: "password"
            - name: QB_CMD_AUTOFILL
              value: "autofill"
            - name: QB_CMD_BLACKLIST
              value: "blacklist"
            - name: QB_CMD_CLEANUP
              value: "cleanup"
            - name: QB_CMD_CLEAR
              value: "clear"
            - name: QB_CMD_COLOR
              value: "color"
            - name: QB_CMD_DISPLAY
              value: "display"
            - name: QB_CMD_GRACE_PERIOD
              value: "grace"
            - name: QB_CMD_HEADER
              value: "header"
            - name: QB_CMD_HELP
              value: "help"
            - name: QB_CMD_JOIN
              value: "join"
            - name: QB_CMD_KICK
              value: "kick"
            - name: QB_CMD_LIMIT
              value: "limit"
            - name: QB_CMD_MENTION
              value: "mention"
            - name: QB_CMD_MODE
              value: "mode"
            - name: QB_CMD_MY_QUEUES
              value: "myqueues"
            - name: QB_CMD_NEXT
              value: "next"
            - name: QB_CMD_PREFIX
              value: "prefix"
            - name: QB_CMD_PULL_NUM
              value: "pullnum"
            - name: QB_CMD_QUEUE
              value: "queue"
            - name: QB_CMD_QUEUE_DELETE
              value: "delete"
            - name: QB_CMD_SHUFFLE
              value: "shuffle"
            - name: QB_CMD_START
              value: "start"
            - name: QB_CMD_WHITELIST
              value: "whitelist"
          resources:
            requests:
              cpu: 50m
              memory: 100M